AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for creating an OIDC provider for GitHub Actions'

Parameters:
  githubUser:
    Default: rrigato
    Description: 'GitHub organization name'
    Type: String

  oidcAudience:
    Default: 'sts.amazonaws.com'
    Description: 'The audience for the OIDC provider'
    Type: String

  projectName:
    Default: rewatch
    Description: 'Same as github repository name'
    Type: String

Resources:
  githubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 1b511abead59c6ce207077c0bf0e0043b1382612

  projectRoleForGitHubActions:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref githubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref oidcAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${githubUser}/${projectName}:*

  projectRolePermissionsPolicies: 
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: 'githubActionsPermissions'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Action:
              - 'dynamodb:ListTables'
              - 'dynamodb:ListBackups'
            Resource: '*'
      Roles: 
        - Ref: 'projectRoleForGitHubActions'