name: rewatch application pipeline
on: 
  push: 
    branches:
      - master

jobs:
  run-build-test:
    runs-on: ubuntu-latest
    name: Build and tests application code and updates archives to s3
    steps:
      - name: checkout-current-branch
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: script-execution-permissions
        run: chmod +x '.github/scripts/rewatch_build_test.sh'

      - name: test-and-build-deployment-archive
        shell: bash
        env: 
          PROJECT_NAME: 'rewatch'
          REGION_NAME: 'us-east-1'
        run: '.github/scripts/rewatch_build_test.sh'
